export const locales = ['en', 'zh', 'es', 'hi', 'ar', 'pt', 'bn', 'ru', 'ja', 'fr'] as const
export type Locale = (typeof locales)[number]

export const localeNames: Record<Locale, string> = {
  en: 'English', zh: '中文', es: 'Español', hi: 'हिन्दी', ar: 'العربية',
  pt: 'Português', bn: 'বাংলা', ru: 'Русский', ja: '日本語', fr: 'Français',
}

const en = {
  tagline: 'Probabilistic Battleship engine: exact endgame enumeration and weighted Monte Carlo during play — the best move under the current model.',
  shots: 'Shots', hits: 'Hits', accuracy: 'Accuracy', undo: 'Undo', redo: 'Redo', turn: 'Turn',
  cellHint: 'click a cell to record the result', boardHint: 'Click a cell to record a shot; right-click to erase. The pulsing outline marks the best shot. Ctrl+Z undoes.',
  bestShot: 'best shot', probability: 'probability', miss: 'miss', hit: 'hit', sunk: 'sunk', empty: 'certainly empty',
  recommendation: 'Recommendation', calculating: 'Calculating…', hunt: 'Hunt', target: 'Target', victory: 'Victory', conflict: 'Conflict',
  wonText: 'Victory! The enemy fleet is destroyed.', conflictText: 'Board marks contradict the rules. Check hits and sunk ships or switch the rule set.',
  hitProbability: 'hit probability', relativeWeight: 'relative weight', alternatives: 'Alternatives', method: 'Method', configurations: 'configurations', samples: 'samples', effective: 'effective', strategy: 'Strategy', untilVictory: 'shots to victory',
  enemyFleet: 'Enemy fleet', afloat: 'afloat', fleetSunk: 'sunk', fleetUnknown: 'Fleet unavailable',
  settings: 'Settings', rules: 'Rules', russian: 'Russian (classic)', russianSub: '4·3·3·2·2·2·1·1·1·1, ships cannot touch', international: 'International', internationalSub: '5·4·3·3·2, touching allowed', heatmap: 'Heat map', percentages: 'Cell percentages', resetYes: 'Yes, reset', cancel: 'Cancel', newGame: 'New game',
  howTo: 'How to use', step1: 'Fire at the cell with the pulsing orange outline.', step2: 'Click the cell and record Miss, Hit, or Sunk.', step3: 'The engine recalculates probabilities; repeat until victory.',
  opponentBoard: 'Opponent board', unshot: 'unshot', resultFor: 'Shot result for', erase: 'Erase', shipLength: 'Length of sunk ship:', shipWhere: 'Where was the ship?', language: 'Language',
  invalidLine: 'Hits do not form a straight line', noSegment: 'No matching hit segment of this length',
  exactEnum: 'exact enumeration', weightedMc: 'weighted Monte Carlo', density: 'density heuristic', expectimax: 'expectimax (minimum expected shots)', lookahead: 'probability + two-ply lookahead', maxprob: 'maximum probability',
}
export type Messages = typeof en

const dictionaries: Record<Locale, Messages> = {
  en,
  ru: { ...en, tagline:'Вероятностный движок «Морского боя»: точный перебор в эндшпиле и взвешенное Монте-Карло в партии — лучший ход по текущей модели.', shots:'Выстрелов',hits:'Попаданий',accuracy:'Точность',undo:'Отменить',redo:'Повторить',turn:'Ход',cellHint:'клик по клетке — выбор результата',boardHint:'Клик по клетке — отметить результат, правый клик — стереть. Пульсирующая рамка — лучший выстрел. Ctrl+Z — отмена.',bestShot:'лучший выстрел',probability:'вероятность',miss:'промах',hit:'ранен',sunk:'потоплен',empty:'точно пусто',recommendation:'Рекомендация',calculating:'Расчёт…',hunt:'Поиск',target:'Добивание',victory:'Победа',conflict:'Противоречие',wonText:'Победа! Флот противника уничтожен.',conflictText:'Отметки на поле противоречат правилам. Проверьте попадания и потопленные корабли или смените правила.',hitProbability:'вероятность попадания',relativeWeight:'относительный вес',alternatives:'Альтернативы',method:'Метод',configurations:'конфигураций',samples:'сэмплов',effective:'эфф.',strategy:'Стратегия',untilVictory:'выстр. до победы',enemyFleet:'Флот противника',afloat:'в строю',fleetSunk:'потоплен',fleetUnknown:'Флот не определён',settings:'Настройки',rules:'Правила',russian:'Русские (классика)',russianSub:'4·3·3·2·2·2·1·1·1·1, корабли не касаются',international:'Международные',internationalSub:'5·4·3·3·2, касание разрешено',heatmap:'Тепловая карта',percentages:'Проценты в клетках',resetYes:'Да, сбросить',cancel:'Отмена',newGame:'Новая игра',howTo:'Как пользоваться',step1:'Стреляйте в клетку с мигающей оранжевой рамкой.',step2:'Кликните по клетке и выберите: «Мимо», «Ранил» или «Убил».',step3:'Движок пересчитает вероятности — повторяйте до победы.',opponentBoard:'Поле противника',unshot:'не обстреляно',resultFor:'Результат выстрела в',erase:'Стереть',shipLength:'Длина потопленного корабля:',shipWhere:'Где стоял корабль?',language:'Язык',invalidLine:'Ранения не образуют прямую линию',noSegment:'Нет подходящего отрезка ранений этой длины',exactEnum:'точный перебор',weightedMc:'взвешенное Монте-Карло',density:'эвристика плотности',expectimax:'expectimax (минимум матожидания)',lookahead:'вероятность + двухходовый разбор',maxprob:'максимум вероятности' },
  es: { ...en, tagline:'Motor probabilístico de Batalla Naval: enumeración exacta al final y Monte Carlo ponderado durante la partida.',shots:'Disparos',hits:'Impactos',accuracy:'Precisión',undo:'Deshacer',redo:'Rehacer',turn:'Turno',cellHint:'haz clic para registrar el resultado',boardHint:'Haz clic para registrar un disparo; clic derecho para borrar. El borde pulsante indica el mejor disparo.',bestShot:'mejor disparo',probability:'probabilidad',miss:'agua',hit:'tocado',sunk:'hundido',empty:'vacío seguro',recommendation:'Recomendación',calculating:'Calculando…',hunt:'Búsqueda',target:'Remate',victory:'Victoria',conflict:'Conflicto',wonText:'¡Victoria! La flota enemiga ha sido destruida.',conflictText:'Las marcas contradicen las reglas. Revisa impactos y barcos hundidos.',hitProbability:'probabilidad de impacto',relativeWeight:'peso relativo',alternatives:'Alternativas',method:'Método',configurations:'configuraciones',samples:'muestras',effective:'efectivas',strategy:'Estrategia',untilVictory:'disparos hasta ganar',enemyFleet:'Flota enemiga',afloat:'a flote',fleetSunk:'hundido',fleetUnknown:'Flota no disponible',settings:'Ajustes',rules:'Reglas',russian:'Rusa (clásica)',russianSub:en.russianSub,international:'Internacional',internationalSub:'5·4·3·3·2, se permite contacto',heatmap:'Mapa de calor',percentages:'Porcentajes',resetYes:'Sí, reiniciar',cancel:'Cancelar',newGame:'Nueva partida',howTo:'Cómo usar',step1:'Dispara a la celda con el borde naranja pulsante.',step2:'Marca Agua, Tocado o Hundido.',step3:'El motor recalcula las probabilidades; repite hasta ganar.',opponentBoard:'Tablero rival',unshot:'sin disparar',resultFor:'Resultado del disparo en',erase:'Borrar',shipLength:'Longitud del barco hundido:',shipWhere:'¿Dónde estaba el barco?',language:'Idioma',invalidLine:'Los impactos no forman una línea recta',noSegment:'No hay un segmento válido de esta longitud',exactEnum:'enumeración exacta',weightedMc:'Monte Carlo ponderado',density:'heurística de densidad',expectimax:en.expectimax,lookahead:'probabilidad + análisis a dos jugadas',maxprob:'probabilidad máxima' },
  fr: { ...en, tagline:'Moteur probabiliste de bataille navale : énumération exacte en fin de partie et Monte-Carlo pondéré.',shots:'Tirs',hits:'Touches',accuracy:'Précision',undo:'Annuler',redo:'Rétablir',turn:'Tour',cellHint:'cliquez pour saisir le résultat',boardHint:'Cliquez pour saisir un tir, clic droit pour effacer. Le contour pulsant indique le meilleur tir.',bestShot:'meilleur tir',probability:'probabilité',miss:'raté',hit:'touché',sunk:'coulé',empty:'certainement vide',recommendation:'Recommandation',calculating:'Calcul…',hunt:'Recherche',target:'Ciblage',victory:'Victoire',conflict:'Conflit',wonText:'Victoire ! La flotte ennemie est détruite.',conflictText:'Les marques contredisent les règles. Vérifiez les touches et navires coulés.',hitProbability:'probabilité de toucher',relativeWeight:'poids relatif',alternatives:'Alternatives',method:'Méthode',configurations:'configurations',samples:'échantillons',effective:'effectifs',strategy:'Stratégie',untilVictory:'tirs avant victoire',enemyFleet:'Flotte ennemie',afloat:'à flot',fleetSunk:'coulé',fleetUnknown:'Flotte indisponible',settings:'Paramètres',rules:'Règles',russian:'Russe (classique)',russianSub:en.russianSub,international:'International',internationalSub:'5·4·3·3·2, contact autorisé',heatmap:'Carte thermique',percentages:'Pourcentages',resetYes:'Oui, réinitialiser',cancel:'Annuler',newGame:'Nouvelle partie',howTo:'Utilisation',step1:'Tirez sur la case au contour orange pulsant.',step2:'Indiquez Raté, Touché ou Coulé.',step3:'Le moteur recalcule les probabilités ; répétez jusqu’à la victoire.',opponentBoard:'Grille adverse',unshot:'non ciblé',resultFor:'Résultat du tir en',erase:'Effacer',shipLength:'Longueur du navire coulé :',shipWhere:'Où était le navire ?',language:'Langue',invalidLine:'Les touches ne forment pas une ligne droite',noSegment:'Aucun segment valide de cette longueur',exactEnum:'énumération exacte',weightedMc:'Monte-Carlo pondéré',density:'heuristique de densité',expectimax:en.expectimax,lookahead:'probabilité + analyse à deux coups',maxprob:'probabilité maximale' },
  pt: { ...en, tagline:'Motor probabilístico de Batalha Naval: enumeração exata no fim e Monte Carlo ponderado durante o jogo.',shots:'Tiros',hits:'Acertos',accuracy:'Precisão',undo:'Desfazer',redo:'Refazer',turn:'Turno',cellHint:'clique para registrar o resultado',boardHint:'Clique para registrar um tiro; botão direito para apagar. A borda pulsante marca o melhor tiro.',bestShot:'melhor tiro',probability:'probabilidade',miss:'água',hit:'atingido',sunk:'afundado',empty:'certamente vazio',recommendation:'Recomendação',calculating:'Calculando…',hunt:'Busca',target:'Alvo',victory:'Vitória',conflict:'Conflito',wonText:'Vitória! A frota inimiga foi destruída.',conflictText:'As marcações contradizem as regras. Verifique acertos e navios afundados.',hitProbability:'probabilidade de acerto',relativeWeight:'peso relativo',alternatives:'Alternativas',method:'Método',configurations:'configurações',samples:'amostras',effective:'efetivas',strategy:'Estratégia',untilVictory:'tiros até vencer',enemyFleet:'Frota inimiga',afloat:'ativo',fleetSunk:'afundado',fleetUnknown:'Frota indisponível',settings:'Configurações',rules:'Regras',russian:'Russa (clássica)',russianSub:en.russianSub,international:'Internacional',internationalSub:'5·4·3·3·2, contato permitido',heatmap:'Mapa de calor',percentages:'Porcentagens',resetYes:'Sim, reiniciar',cancel:'Cancelar',newGame:'Novo jogo',howTo:'Como usar',step1:'Atire na célula com a borda laranja pulsante.',step2:'Marque Água, Atingido ou Afundado.',step3:'O motor recalcula as probabilidades; repita até vencer.',opponentBoard:'Tabuleiro adversário',unshot:'não alvejado',resultFor:'Resultado do tiro em',erase:'Apagar',shipLength:'Comprimento do navio afundado:',shipWhere:'Onde estava o navio?',language:'Idioma',invalidLine:'Os acertos não formam uma linha reta',noSegment:'Nenhum segmento válido deste tamanho',exactEnum:'enumeração exata',weightedMc:'Monte Carlo ponderado',density:'heurística de densidade',expectimax:en.expectimax,lookahead:'probabilidade + análise de duas jogadas',maxprob:'probabilidade máxima' },
  zh: { ...en, tagline:'概率战舰引擎：残局精确枚举，游戏中使用加权蒙特卡洛，给出当前模型下的最佳射击。',shots:'射击',hits:'命中',accuracy:'命中率',undo:'撤销',redo:'重做',turn:'回合',cellHint:'点击格子记录结果',boardHint:'点击记录射击，右键擦除。闪烁边框表示最佳射击。Ctrl+Z 撤销。',bestShot:'最佳射击',probability:'概率',miss:'未中',hit:'命中',sunk:'击沉',empty:'确定为空',recommendation:'建议',calculating:'计算中…',hunt:'搜索',target:'追击',victory:'胜利',conflict:'冲突',wonText:'胜利！敌方舰队已被摧毁。',conflictText:'棋盘标记与规则冲突。请检查命中和击沉记录。',hitProbability:'命中概率',relativeWeight:'相对权重',alternatives:'备选',method:'方法',configurations:'配置',samples:'样本',effective:'有效',strategy:'策略',untilVictory:'距胜利射击数',enemyFleet:'敌方舰队',afloat:'在役',fleetSunk:'已沉',fleetUnknown:'舰队不可用',settings:'设置',rules:'规则',russian:'俄式（经典）',russianSub:en.russianSub,international:'国际规则',internationalSub:'5·4·3·3·2，允许接触',heatmap:'热力图',percentages:'格内百分比',resetYes:'确认重置',cancel:'取消',newGame:'新游戏',howTo:'使用方法',step1:'向闪烁橙色边框的格子射击。',step2:'点击格子并记录未中、命中或击沉。',step3:'引擎会重新计算概率，重复直到胜利。',opponentBoard:'对手棋盘',unshot:'未射击',resultFor:'射击结果',erase:'擦除',shipLength:'被击沉舰船长度：',shipWhere:'舰船在哪里？',language:'语言',invalidLine:'命中点不在直线上',noSegment:'没有该长度的有效命中段',exactEnum:'精确枚举',weightedMc:'加权蒙特卡洛',density:'密度启发式',expectimax:'期望极大化（最少期望射击）',lookahead:'概率 + 两步前瞻',maxprob:'最大概率' },
  ja: { ...en, tagline:'確率的な海戦ゲームエンジン。終盤は完全列挙、対局中は重み付きモンテカルロで最善手を提案します。',shots:'射撃',hits:'命中',accuracy:'命中率',undo:'元に戻す',redo:'やり直す',turn:'ターン',cellHint:'マスをクリックして結果を記録',boardHint:'クリックで射撃を記録、右クリックで消去。点滅枠が最善手です。',bestShot:'最善の射撃',probability:'確率',miss:'外れ',hit:'命中',sunk:'撃沈',empty:'確実に空',recommendation:'推奨',calculating:'計算中…',hunt:'探索',target:'追撃',victory:'勝利',conflict:'矛盾',wonText:'勝利！敵艦隊を撃破しました。',conflictText:'盤面の記録がルールと矛盾しています。命中と撃沈を確認してください。',hitProbability:'命中確率',relativeWeight:'相対重み',alternatives:'候補',method:'手法',configurations:'配置',samples:'サンプル',effective:'有効',strategy:'戦略',untilVictory:'勝利までの射撃',enemyFleet:'敵艦隊',afloat:'健在',fleetSunk:'撃沈',fleetUnknown:'艦隊不明',settings:'設定',rules:'ルール',russian:'ロシア式（クラシック）',russianSub:en.russianSub,international:'国際式',internationalSub:'5·4·3·3·2、接触可',heatmap:'ヒートマップ',percentages:'確率表示',resetYes:'リセットする',cancel:'キャンセル',newGame:'新しいゲーム',howTo:'使い方',step1:'オレンジ色に点滅するマスを撃ちます。',step2:'外れ、命中、撃沈を記録します。',step3:'確率が再計算されます。勝利まで繰り返します。',opponentBoard:'相手の盤面',unshot:'未射撃',resultFor:'射撃結果',erase:'消去',shipLength:'撃沈した艦の長さ：',shipWhere:'艦はどこにありましたか？',language:'言語',invalidLine:'命中が直線を形成していません',noSegment:'この長さの有効な区間がありません',exactEnum:'完全列挙',weightedMc:'重み付きモンテカルロ',density:'密度ヒューリスティック',expectimax:'expectimax（期待射撃数を最小化）',lookahead:'確率 + 2手先読み',maxprob:'最大確率' },
  hi: { ...en, tagline:'संभाव्य बैटलशिप इंजन: अंत में सटीक गणना और खेल के दौरान भारित मोंटे कार्लो।',shots:'शॉट',hits:'हिट',accuracy:'सटीकता',undo:'पूर्ववत',redo:'फिर करें',turn:'चाल',cellHint:'परिणाम दर्ज करने के लिए खाने पर क्लिक करें',boardHint:'शॉट दर्ज करने के लिए क्लिक करें; मिटाने के लिए दायाँ क्लिक। चमकती सीमा सर्वोत्तम शॉट है।',bestShot:'सर्वोत्तम शॉट',probability:'संभावना',miss:'चूक',hit:'हिट',sunk:'डूबा',empty:'निश्चित खाली',recommendation:'सुझाव',calculating:'गणना…',hunt:'खोज',target:'लक्ष्य',victory:'जीत',conflict:'विरोध',wonText:'जीत! दुश्मन का बेड़ा नष्ट हो गया।',conflictText:'बोर्ड के निशान नियमों से मेल नहीं खाते। हिट और डूबे जहाज़ जाँचें।',hitProbability:'हिट की संभावना',relativeWeight:'सापेक्ष भार',alternatives:'विकल्प',method:'विधि',configurations:'विन्यास',samples:'नमूने',effective:'प्रभावी',strategy:'रणनीति',untilVictory:'जीत तक शॉट',enemyFleet:'दुश्मन बेड़ा',afloat:'सक्रिय',fleetSunk:'डूबा',fleetUnknown:'बेड़ा उपलब्ध नहीं',settings:'सेटिंग्स',rules:'नियम',russian:'रूसी (क्लासिक)',russianSub:en.russianSub,international:'अंतरराष्ट्रीय',internationalSub:'5·4·3·3·2, स्पर्श मान्य',heatmap:'हीट मैप',percentages:'प्रतिशत',resetYes:'हाँ, रीसेट',cancel:'रद्द करें',newGame:'नया खेल',howTo:'कैसे उपयोग करें',step1:'चमकती नारंगी सीमा वाले खाने पर गोली चलाएँ।',step2:'चूक, हिट या डूबा दर्ज करें।',step3:'इंजन संभावनाएँ फिर गिनता है; जीत तक दोहराएँ।',opponentBoard:'विरोधी बोर्ड',unshot:'बिना शॉट',resultFor:'शॉट का परिणाम',erase:'मिटाएँ',shipLength:'डूबे जहाज़ की लंबाई:',shipWhere:'जहाज़ कहाँ था?',language:'भाषा',invalidLine:'हिट सीधी रेखा में नहीं हैं',noSegment:'इस लंबाई का मान्य खंड नहीं है',exactEnum:'सटीक गणना',weightedMc:'भारित मोंटे कार्लो',density:'घनत्व अनुमान',expectimax:en.expectimax,lookahead:'संभावना + दो-चाल विश्लेषण',maxprob:'अधिकतम संभावना' },
  ar: { ...en, tagline:'محرك احتمالي للعبة السفن: تعداد دقيق في النهاية ومونت كارلو موزون أثناء اللعب.',shots:'الطلقات',hits:'الإصابات',accuracy:'الدقة',undo:'تراجع',redo:'إعادة',turn:'الدور',cellHint:'انقر على خلية لتسجيل النتيجة',boardHint:'انقر لتسجيل طلقة، وانقر بزر الفأرة الأيمن للمسح. الإطار النابض يحدد أفضل طلقة.',bestShot:'أفضل طلقة',probability:'الاحتمال',miss:'خطأ',hit:'إصابة',sunk:'غارقة',empty:'فارغة بالتأكيد',recommendation:'التوصية',calculating:'جارٍ الحساب…',hunt:'بحث',target:'استهداف',victory:'فوز',conflict:'تعارض',wonText:'فوز! تم تدمير أسطول الخصم.',conflictText:'علامات اللوحة تتعارض مع القواعد. تحقق من الإصابات والسفن الغارقة.',hitProbability:'احتمال الإصابة',relativeWeight:'الوزن النسبي',alternatives:'البدائل',method:'الطريقة',configurations:'التكوينات',samples:'العينات',effective:'الفعالة',strategy:'الاستراتيجية',untilVictory:'طلقات حتى الفوز',enemyFleet:'أسطول الخصم',afloat:'عاملة',fleetSunk:'غارقة',fleetUnknown:'الأسطول غير متاح',settings:'الإعدادات',rules:'القواعد',russian:'روسية (كلاسيكية)',russianSub:en.russianSub,international:'دولية',internationalSub:'5·4·3·3·2، يسمح بالتلامس',heatmap:'الخريطة الحرارية',percentages:'النسب',resetYes:'نعم، إعادة ضبط',cancel:'إلغاء',newGame:'لعبة جديدة',howTo:'طريقة الاستخدام',step1:'أطلق على الخلية ذات الإطار البرتقالي النابض.',step2:'سجّل خطأ أو إصابة أو غارقة.',step3:'يعيد المحرك حساب الاحتمالات؛ كرر حتى الفوز.',opponentBoard:'لوحة الخصم',unshot:'لم تُطلق',resultFor:'نتيجة الطلقة في',erase:'مسح',shipLength:'طول السفينة الغارقة:',shipWhere:'أين كانت السفينة؟',language:'اللغة',invalidLine:'الإصابات لا تشكل خطًا مستقيمًا',noSegment:'لا يوجد مقطع صالح بهذا الطول',exactEnum:'تعداد دقيق',weightedMc:'مونت كارلو موزون',density:'تقدير الكثافة',expectimax:en.expectimax,lookahead:'احتمال + تحليل خطوتين',maxprob:'أقصى احتمال' },
  bn: { ...en, tagline:'সম্ভাব্য ব্যাটলশিপ ইঞ্জিন: শেষ পর্যায়ে নির্ভুল গণনা এবং খেলায় ওজনযুক্ত মন্টে কার্লো।',shots:'শট',hits:'হিট',accuracy:'নির্ভুলতা',undo:'পূর্বাবস্থা',redo:'পুনরায়',turn:'চাল',cellHint:'ফল লিখতে ঘরে ক্লিক করুন',boardHint:'শট লিখতে ক্লিক করুন; মুছতে ডান ক্লিক। স্পন্দিত সীমা সেরা শট।',bestShot:'সেরা শট',probability:'সম্ভাবনা',miss:'মিস',hit:'হিট',sunk:'ডুবেছে',empty:'নিশ্চিত খালি',recommendation:'পরামর্শ',calculating:'গণনা হচ্ছে…',hunt:'অনুসন্ধান',target:'লক্ষ্য',victory:'জয়',conflict:'অসঙ্গতি',wonText:'জয়! শত্রু নৌবহর ধ্বংস হয়েছে।',conflictText:'বোর্ডের চিহ্ন নিয়মের সঙ্গে মেলে না। হিট ও ডোবা জাহাজ যাচাই করুন।',hitProbability:'হিটের সম্ভাবনা',relativeWeight:'আপেক্ষিক ওজন',alternatives:'বিকল্প',method:'পদ্ধতি',configurations:'বিন্যাস',samples:'নমুনা',effective:'কার্যকর',strategy:'কৌশল',untilVictory:'জয় পর্যন্ত শট',enemyFleet:'শত্রু নৌবহর',afloat:'সক্রিয়',fleetSunk:'ডুবেছে',fleetUnknown:'নৌবহর অনুপলব্ধ',settings:'সেটিংস',rules:'নিয়ম',russian:'রুশ (ক্লাসিক)',russianSub:en.russianSub,international:'আন্তর্জাতিক',internationalSub:'5·4·3·3·2, স্পর্শ অনুমোদিত',heatmap:'হিট ম্যাপ',percentages:'শতাংশ',resetYes:'হ্যাঁ, রিসেট',cancel:'বাতিল',newGame:'নতুন খেলা',howTo:'ব্যবহারবিধি',step1:'স্পন্দিত কমলা সীমার ঘরে গুলি করুন।',step2:'মিস, হিট বা ডুবেছে লিখুন।',step3:'ইঞ্জিন সম্ভাবনা পুনর্গণনা করে; জয় পর্যন্ত চালিয়ে যান।',opponentBoard:'প্রতিপক্ষের বোর্ড',unshot:'গুলি হয়নি',resultFor:'শটের ফল',erase:'মুছুন',shipLength:'ডোবা জাহাজের দৈর্ঘ্য:',shipWhere:'জাহাজটি কোথায় ছিল?',language:'ভাষা',invalidLine:'হিটগুলো সরলরেখায় নেই',noSegment:'এই দৈর্ঘ্যের বৈধ অংশ নেই',exactEnum:'নির্ভুল গণনা',weightedMc:'ওজনযুক্ত মন্টে কার্লো',density:'ঘনত্ব অনুমান',expectimax:en.expectimax,lookahead:'সম্ভাবনা + দুই চাল বিশ্লেষণ',maxprob:'সর্বোচ্চ সম্ভাবনা' },
}

export function getMessages(locale: Locale): Messages { return dictionaries[locale] }
export function detectLocale(value: string): Locale {
  const code = value.toLowerCase().split('-')[0]
  return locales.includes(code as Locale) ? (code as Locale) : 'en'
}
export function localeDirection(locale: Locale): 'ltr' | 'rtl' { return locale === 'ar' ? 'rtl' : 'ltr' }
